version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
        - '80:80'
    volumes:
        - ./nginx:/etc/nginx/conf.d
        - ./logs/nginx:/var/log/nginx
        - ./code:/var/www/html
    links:
        - web
    restart: always

  web:
    image: 'php:7.3.1-fpm'
    volumes:
      - ./code:/var/www/html
    ports:
      - '9000:9000'
    restart: always
    user: 1000:1000

